char *Pokemon[190] = 

  {  "  Rhydon"       ,
     "  Kangaskhan"   ,
     "  Nidoran|M|"   ,
     "  Clefairy"     ,
     "  Spearow"      ,
     "  Voltorb"      ,
     "  Nidoking"     ,
     "  Slobro"       ,
     "  Ivysaur"      ,
     "  Exeggutor"    ,
     "  Lickitung"    ,
     "  Exeggute"     ,
     "  Grimer"       ,
     "  Gengar"       ,
     "  Nidoran|F|"   ,
     "  Nidoqueen"    ,
     "  Cubone"       ,
     "  Rhyhorn"      ,
     "  Lapras"       ,
     "  Arcanine"     ,
     "  Mew"          ,
     "  Gyarodose"    ,
     "  Shellder"     ,
     "  Tentacool"    ,
     "  Gastly"       ,
     "  Scyther"      ,
     "  Staryu"       ,
     "  Blastoise"    ,
     "  Pinser"       ,
     "  Tangela"      ,
     "* Scizor"       ,
     "* Shuckle"      ,
     "  Growlithe"    ,
     "  Onix"         ,
     "  Fearow"       ,
     "  Pidgey"       ,
     "  Slowpoke"     ,
     "  Kadabra"      ,
     "  Graveler"     ,
     "  Chansey"      ,
     "  Machoke"      ,
     "  Mr. Mime"     ,
     "  Hitmonlee"    ,
     "  Hitmonchan"   ,
     "  Arbok"        ,
     "  Parasect"     ,
     "  Psyduck"      ,
     "  Drowzee"      ,
     "  Golem"        ,
     "* Heracross"    ,
     "  Magmar"       ,
     "* Ho-Oh"        ,
     "  Electabuzz"   ,
     "  Magneton"     ,
     "  Koffing"      ,
     "* Sneasel"      ,
     "  Mankey"       ,
     "  Seel"         ,
     "  Diglet"       ,
     "  Tauros"       ,
     "* Teddiursa"    ,
     "* Ursaring"     ,
     "* Slugma"       ,
     "  Farfetch'd"   ,
     "  Venonat"      ,
     "  Dragonite"    ,
     "* Magcargo"     ,
     "* Swinub"       ,
     "* Piloswine"    ,
     "  Doduo"        ,
     "  Poliwag"      ,
     "  Jynx"         ,
     "  Moltres"      ,
     "  Articuno"     ,
     "  Zaptos"       ,
     "  Ditto"        ,
     "  Meouth"       ,
     "  Krabby"       ,
     "* Corsola"      ,
     "* Remoraid"     ,
     "* Octillery"    ,
     "  Vulpix"       ,
     "  Ninetails"    ,
     "  Pikachu"      ,
     "  Riachu"       ,
     "* Delibird"     ,
     "* Mantine"      ,
     "  Dratini"      ,
     "  Dragonair"    ,
     "  Kabuto"       ,
     "  Kabutops"     ,
     "  Horsea"       ,
     "  Seadra"       ,
     "* Skarmory"     ,
     "* Houndour"     ,
     "  Sandshrew"    ,
     "  Sandslash"    ,
     "  Omanyte"      ,
     "  Omastar"      ,
     "  Jigglypuff"   ,
     "  Wigglytuff"   ,
     "  Eevee"        ,
     "  Flareon"      ,
     "  Jolteon"      ,
     "  Vaporeon"     ,
     "  Machop"       ,
     "  Zubat"        ,
     "  Ekans"        ,
     "  Paras"        ,
     "  Poliwhirl"    ,
     "  Poliwrath"    ,
     "  Weedle"       ,
     "  kakuna"       ,
     "  Beedril"      ,
     "* Houndoom"     ,
     "  Dodrio"       ,
     "  Primeape"     ,
     "  Dugtrio"      ,
     "  Venomoth"     ,
     "  Dewgong"      ,
     "* Kingdra"      ,
     "* Phanpy"       ,
     "  Caterpie"     ,
     "  Metapod"      ,
     "  Butterfree"   ,
     "  Machamp"      ,
     "* Donphan"      ,
     "  Golduck"      ,
     "  Hypno"        ,
     "  Golbat"       ,
     "  Mewtwo"       ,
     "  Snorlax"      ,
     "  Magikarp"     ,
     "* Porygon2"     ,
     "* Stantler"     ,
     "  Muk"          ,
     "* Smeargle"     ,
     "  Kingler"      ,
     "  Cloyster"     ,
     "* Tyrougue"     ,
     "  Electrode"    ,
     "  Clefable"     ,
     "  Weezing"      ,
     "  Persian"      ,
     "  Marrowak"     ,
     "* Hitmontop"    ,
     "  Haunter"      ,
     "  Abra"         ,
     "  Alakazam"     ,
     "  Pidgeotto"    ,
     "  Pidgeot"      ,
     "  Starmie"      ,
     "  Bulbasaur"    ,
     "  Venusaur"     ,
     "  Tentacruel"   ,
     "* Smoochum"     ,
     "  Goldeen"      ,
     "  Seaking"      ,
     "* Elekid"       ,
     "* Magby"        ,
     "* Miltank"      ,
     "* Blissey"      ,
     "  Ponyta"       ,
     "  Rapidash"     ,
     "  Rattata"      ,
     "  Raticate"     ,
     "  Nidorino"     ,
     "  Nidorina"     ,
     "  Geodudue"     ,
     "  Porygon"      ,
     "  Aerodactyl"   ,
     "* Raikou"       ,
     "  Magnemite"    ,
     "* Entei"        ,
     "* Suicune"      ,
     "  Charmander"   ,
     "  Squirtle"     ,
     "  Charmeleon"   ,
     "  Wartortle"    ,
     "  Charizard"    ,
     "* Lavitar"      ,
     "* Pupitar"      ,
     "* Tyranitar"    ,
     "* Lugia"        ,
     "  Oddish"       ,
     "  Gloom"        ,
     "  Vileplume"    ,
     "  Bellsprout"   ,
     "  Weepinbell"   ,
     "  Victreebell"  };   

char *Moves[165]  {
     
  "Pound",
  "Karate",
  "Chop*",
  "Double",
  "Slap",
  "Comet",
  "Punch",
  "Mega",
  "Punch",
  "Pay",
  "Day",
  "Fire",
  "Punch",
  "Ice",
  "Punch",
  "Thunder",
  "Punch",
  "Scratch",
  "Vice",
  "Grip",
  "Guillotine",
  "Razor",
  "Wind",
  "Swords",
  "Dance",
  "Cut",
  "Gust*",
  "Wing",
  "Attack",
  "Whirlwind",
  "Fly",
  "Bind",
  "Slam",
  "Vine",
  "WhipI",
  "Stomp",
  "Normal",
  "Double",
  "Kick",
  "Mega",
  "Kick",
  "Jump",
  "Kick",
  "Rolling",
  "Kick",
  "Sand",
  "Attack*",
  "Headbutt",
  "Horn",
  "Attack",
  "Fury",
  "Attack",
  "Horn",
  "Drill",
  "Tackle",
  "Body",
  "Slam",
  "Wrap",
  "Take",
  "Down",
  "Thrash",
  "Double-Edge",
  "Tail",
  "Whip",
  "Poison",
  "Sting",
  "Twineedle",
  "Pin",
  "Missile",
  "Leer",
  "Bite*",
  "Growl",
  "Roar",
  "Sing",
  "Supersonic",
  "Sonic",
  "Boom",
  "Disable",
  "Acid",
  "Ember",
  "Flamethrower",
  "Mist",
  "Water",
  "Gun",
  "Hydro",
  "Pump",
  "Surf",
  "Ice",
  "Beam",
  "Blizzard",
  "Psybeam",
  "Bubble",
  "Beam",
  "Aurora",
  "Beam",
  "Hyper",
  "Beam",
  "Peck",
  "Drill",
  "Peck",
  "Submission",
  "Low",
  "Kick",
  "Counter",
  "Seismic",
  "Toss",
  "Strength",
  "Absorb",
  "Mega",
  "Drain",
  "Leech",
  "Seed",
  "Growth",
  "Razor",
  "Leaf",
  "Solar",
  "Beam",
  "Poison",
  "Powder",
  "Stun",
  "Spore",
  "Sleep",
  "Powder",
  "Petal",
  "Dance",
  "String",
  "Shot",
  "Dragon",
  "Rage",
  "Fire",
  "Spin",
  "Thunder",
  "Shock",
  "Thunderbolt",
  "Thunder",
  "Wave",
  "Thunder",
  "Rock",
  "Throw",
  "Earthquake",
  "Fissure",
  "Dig",
  "Toxic",
  "Confusion",
  "Psychic",
  "Hypnosis",
  "Meditate",
  "Agility",
  "Quick",
  "Attack",
  "Rage",
  "Teleport",
  "Night",
  "Shade",
  "Mimic",
  "Screech",
  "Double",
  "Team",
  "Recover",
  "Harden",
  "Minimize",
  "Smokescreen",
  "Confuse",
  "Ray",
  "Withdraw",
  "Defense",
  "Curl",
  "Barrier",
  "Light",
  "Screen",
  "Haze",
  "Reflect",
  "Focus",
  "Energy",
  "Bide",
  "Metronome",
  "Mirror",
  "Move",
  "Self-Destruct",
  "Egg",
  "Bomb",
  "Lick",
  "Smog",
  "Sludge",
  "Bone",
  "Club",
  "Fire",
  "Blast",
  "Waterfall",
  "Clamp",
  "Swift",
  "Skull",
  "Bash",
  "Spike",
  "Cannon",
  "Constrict",
  "Amnesia",
  "Kinesis",
  "Soft-Boiled",
  "High",
  "Jump",
  "Kick",
  "Glare",
  "Dream",
  "Eater",
  "Poison",
  "Gas",
  "Barrage",
  "Leech",
  "Life",
  "Lovely",
  "Kiss",
  "Sky",
  "Attack",
  "Transform",
  "Bubble",
  "Dizzy",
  "Punch",
  "Spore",
  "Flash",
  "Psywave",
  "Splash",
  "Acid",
  "Armor",
  "Crabhammer",
  "Explosion",
  "Fury",
  "Swipes",
  "Bonemerang",
  "Rest",
  "Rock",
  "Slide",
  "Hyper",
  "Fang",
  "Sharpen",
  "Conversion",
  "Tri",
  "Attack",
  "Super",
  "Fang",
  "Slash",
  "Substitute",
  "Struggle"
  };

     
uint8_t DummyPlug[44] {

  0x52,        //Vulpix
  0x00, 0x5E,  //Current Hp
  0x10,                                                                           
  0x00,
  0x14,                                                                           
  0x14, 0xBE,                                                                          
  0x34,     (pkmn1 attack 1, )                                                                     
6d,      (pkmn1 attack 2, )                                                                      
62,      (pkmn1 attack 3, )                                                                      
35,      (pkmn1 attack 4, )                                                                      
ff,                                                                           
f3,                                                                            
1,       (pkmn1 exp MSB, )                                                                     
1c,     (pkmn1 exp, )                                                                     
d7,      (pkmn1 exp, LSB, )                                                                     
18,                                                                           
7c,                                                                           
1d,                                                                           
f4,                                                                           
19,                                                                           
20,                                                                           
1a,                                                                           
dc,                                                                           
1c,                                                                           
95,                                                                           
a7,                                                                            
5e,                                                                           
19,     (pkmn1 attack 1 pp)                                                                    
a,     (pkmn1 attack 2 pp)                                                                        
1e,    (pkmn1 attack 3 pp)                                                                         
f,     (pkmn1 attack 4 pp)                                                                         
29,    (pkmn1 level)                                                                       
0,     (pkmn1 HP MSB)                                                                       
5e,     (pkmn1 HP LSB)                                                                       
0,      (pkmn1 attack-MSB)                                                                       
37,      (pkmn1 attack-LSB)                                                                      
0,      (def MSB, )                                                                      
33,      (def LSB, )                                                                      
0,      (speed MSB, )                                                                      
46,      (speed LSB, )                                                                      
0,      (special MSB, )                                                                    

void DummyFill(*pokemon_t)  {

  
          
          

